### ISSUE TITLE
Calibration files are missing

### ISSUE THREAD

**Issue by Shuang1997** [liudaqikk/RobotEvt#1]
Hi, thanks for releasing your datasets. But I cannot find the camera infomation (intrinsic matrix, distortion coefficients), could you publish it as well?

**Comment by liudaqikk** [comment]
It's my mistake for the inconvenience. I have uploaded the calibration file to the google drive and explanination is provided in the readme.

**Comment by Shuang1997** [comment]
> It's my mistake for the inconvenience. I have uploaded the calibration file to the google drive and explanination is provided in the readme.

Thank you very much!
